<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="NetArchTest.eNhancedEdition" Version="1.4.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\backend\Cartex.Domain\Cartex.Domain.csproj" />
    <ProjectReference Include="..\..\src\backend\Cartex.Application\Cartex.Application.csproj" />
    <ProjectReference Include="..\..\src\backend\Cartex.Persistence\Cartex.Persistence.csproj" />
    <ProjectReference Include="..\..\src\backend\Cartex.Auth\Cartex.Auth.csproj" />
    <ProjectReference Include="..\..\src\backend\Cartex.Infrastructure\Cartex.Infrastructure.csproj" />
  </ItemGroup>

</Project>
