<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.7.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cartex.Application\Cartex.Application.csproj" />
    <ProjectReference Include="..\Cartex.Domain\Cartex.Domain.csproj" />
    <ProjectReference Include="..\Cartex.Persistence\Cartex.Persistence.csproj" />
    <ProjectReference Include="..\..\shared\Cartex.Shared\Cartex.Shared.csproj" />
  </ItemGroup>

</Project>
