<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\app-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.0.5" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Cartex.UI\Cartex.UI.csproj" />
  </ItemGroup>

  <Target Name="RemoveExternalSingleFilePublishArtifacts"
          AfterTargets="Publish"
          Condition="'$(PublishSingleFile)' == 'true'">
    <ItemGroup>
      <_SingleFilePublishDebugSymbols Include="$(PublishDir)libHarfBuzzSharp.pdb" />
      <_SingleFilePublishDebugSymbols Include="$(PublishDir)libSkiaSharp.pdb" />
    </ItemGroup>
    <Delete Files="@(_SingleFilePublishDebugSymbols)" />
    <RemoveDir Directories="$(PublishDir)LatoFont" />
  </Target>
</Project>
