<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e9553b8d-092a-4bb7-989d-1501d6d43a65</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.0.36" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cartex.Application\Cartex.Application.csproj" />
    <ProjectReference Include="..\Cartex.Auth\Cartex.Auth.csproj" />
    <ProjectReference Include="..\Cartex.Infrastructure\Cartex.Infrastructure.csproj" />
    <ProjectReference Include="..\Cartex.Persistence\Cartex.Persistence.csproj" />
    <ProjectReference Include="..\..\shared\Cartex.Shared\Cartex.Shared.csproj" />
  </ItemGroup>

</Project>
