<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.5" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.1" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.1.0-dev-798" />
    <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
    <PackageReference Include="AsyncImageLoader.Avalonia" Version="3.8.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
    <PackageReference Include="QuestPDF" Version="2026.7.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="Semi.Avalonia" Version="12.0.3" />
    <PackageReference Include="Semi.Avalonia.DataGrid" Version="12.0.0" />
    <PackageReference Include="Irihi.Ursa" Version="2.1.0" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="2.1.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-2m69-gcr7-jv3q" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Cartex.ApiClient\Cartex.ApiClient.csproj" />
    <ProjectReference Include="..\..\shared\Cartex.Shared\Cartex.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Languages\*.json" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\logo.png" />
  </ItemGroup>
</Project>
